@hostname = bsh23.brighton.domains
@endpoint = https://{{hostname}}/ci609/api/sightings

### Send PUT request
PUT {{endpoint}}

> {%
    client.test("Bad method is not allowed", () => {
        client.assert(response.status === 405, "Response status is not 405");
    });
%}
