@hostname = bsh23.brighton.domains
@endpoint = https://{{hostname}}/ci609/api/sightings

### Send POST request
POST {{endpoint}}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="image"; filename="pangolin.jpg"

< ./images/pangolin.jpg

--WebAppBoundary
Content-Disposition: form-data; name="deathType"

fence

--WebAppBoundary
Content-Disposition: form-data; name="time"

1764435302226

--WebAppBoundary
Content-Disposition: form-data; name="latitude"

0.0

--WebAppBoundary
Content-Disposition: form-data; name="longitude"

0.0

--WebAppBoundary
Content-Disposition: form-data; name="accuracy"

1.0
--WebAppBoundary--
Content-Disposition: form-data; name="notes"

This is my note.
--WebAppBoundary--

> {%
    client.test("Request executed successfully", () => {
        client.assert(response.status === 201, "Response status is not 201");
    });
%}

### Send POST request without image
POST {{endpoint}}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="deathType"

fence

--WebAppBoundary
Content-Disposition: form-data; name="time"

1764435302226

--WebAppBoundary
Content-Disposition: form-data; name="latitude"

0.0

--WebAppBoundary
Content-Disposition: form-data; name="longitude"

0.0

--WebAppBoundary
Content-Disposition: form-data; name="accuracy"

1.0
--WebAppBoundary--

> {%
    client.test("No image is a bad request", () => {
        client.assert(response.status === 400, "Response status is not 400");
    });
%}

### Send POST request without death type
POST {{endpoint}}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="image"; filename="pangolin.jpg"

< ./images/pangolin.jpg

--WebAppBoundary
Content-Disposition: form-data; name="time"

1764435302226

--WebAppBoundary
Content-Disposition: form-data; name="latitude"

0.0

--WebAppBoundary
Content-Disposition: form-data; name="longitude"

0.0

--WebAppBoundary
Content-Disposition: form-data; name="accuracy"

1.0
--WebAppBoundary--

> {%
    client.test("Request executed successfully", () => {
        client.assert(response.status === 201, "Response status is not 201");
    });
%}

### Send POST request without note
POST {{endpoint}}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="image"; filename="pangolin.jpg"

< ./images/pangolin.jpg

--WebAppBoundary
Content-Disposition: form-data; name="deathType"

fence

--WebAppBoundary
Content-Disposition: form-data; name="time"

1764435302226

--WebAppBoundary
Content-Disposition: form-data; name="latitude"

0.0

--WebAppBoundary
Content-Disposition: form-data; name="longitude"

0.0

--WebAppBoundary
Content-Disposition: form-data; name="accuracy"

1.0
--WebAppBoundary--

> {%
    client.test("Request executed successfully", () => {
        client.assert(response.status === 201, "Response status is not 201");
    });
%}

### Send POST request with invalid deathType
POST {{endpoint}}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="image"; filename="pangolin.jpg"

< ./images/pangolin.jpg

--WebAppBoundary
Content-Disposition: form-data; name="deathType"

hello

--WebAppBoundary
Content-Disposition: form-data; name="time"

1764435302226

--WebAppBoundary
Content-Disposition: form-data; name="latitude"

0.0

--WebAppBoundary
Content-Disposition: form-data; name="longitude"

0.0

--WebAppBoundary
Content-Disposition: form-data; name="accuracy"

1.0
--WebAppBoundary--

> {%
    client.test("Non-integer time is a bad request", () => {
        client.assert(response.status === 400, "Response status is not 400");
    });
%}

### Send POST request with invalid time
POST {{endpoint}}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="image"; filename="pangolin.jpg"

< ./images/pangolin.jpg

--WebAppBoundary
Content-Disposition: form-data; name="time"

hello

--WebAppBoundary
Content-Disposition: form-data; name="latitude"

0.0

--WebAppBoundary
Content-Disposition: form-data; name="longitude"

0.0

--WebAppBoundary
Content-Disposition: form-data; name="accuracy"

1.0
--WebAppBoundary--

> {%
    client.test("Non-integer time is a bad request", () => {
        client.assert(response.status === 400, "Response status is not 400");
    });
%}

### Send POST request with invalid latitude
POST {{endpoint}}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="image"; filename="pangolin.jpg"

< ./images/pangolin.jpg

--WebAppBoundary
Content-Disposition: form-data; name="time"

1764435302226

--WebAppBoundary
Content-Disposition: form-data; name="latitude"

whoops

--WebAppBoundary
Content-Disposition: form-data; name="longitude"

0.0

--WebAppBoundary
Content-Disposition: form-data; name="accuracy"

1.0
--WebAppBoundary--

> {%
    client.test("Non-double latitude is a bad request", () => {
        client.assert(response.status === 400, "Response status is not 400");
    });
%}
