openapi: 3.1.0
info:
  title: Zap App REST API
  version: 1.0.0
servers:
  - url: https://bsh23.brighton.domains/ci609/assignment1/api
paths:
  /sightings:
    post:
      summary: Add a Pangolin sighting
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                deathType:
                  $ref: "#/components/schemas/DeathType"
                time:
                  type: integer
                latitude:
                  type: number
                  format: double
                longitude:
                  type: number
                  format: double
                accuracy:
                  type: number
                  format: double
                image:
                  type: string
                  format: binary
                notes:
                  nullable: true
                  type: string
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PostResponse"
        "400":
          description: Bad Request
components:
  schemas:
    DeathType:
      type: string
      nullable: true
      enum:
        - fence
        - fenceElectrocuted
        - road
        - other
        - null

    PostResponse:
      type: object
      properties:
        id:
          type: integer
      example:
        id: 1

  
