openapi: 3.1.0
info:
  title: Zap App REST API
  version: 1.0.0
servers:
  - url: https://bsh23.brighton.domains/ci609/assignment1/api
paths:
  /sightings:
    post:
      summary: Add a pangolin sighting
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              allOf:
                - type: object
                - properties:
                    image:
                      type: string
                      format: binary
                      description: "Picture of the pangolin. Maximum file size: 2M"
                - $ref: "#/components/schemas/Sighting"
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PostResponse"
        "400":
          description: Bad Request
    get:
      summary: Get a list of pangolin sightings
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  allOf:
                    - type: object
                    - properties:
                        id:
                          type: integer
                        image:
                          type: string
                          format: uri
                    - $ref: "#/components/schemas/SightingPreview"
        "204":
          description: No Content

  /sightings/{id}:
    get:
      summary: Get information about a specific pangolin sighting by ID
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: Unique ID of the pangolin sighting
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  - type: object
                  - properties:
                      id:
                        type: integer
                      image:
                        type: string
                        format: uri
                  - $ref: "#/components/schemas/Sighting"
        "404":
          description: Not Found

components:
  schemas:
    DeathType:
      type: string
      nullable: true
      enum:
        - fence
        - fenceElectrocuted
        - road
        - other
        - null
    PostResponse:
      type: object
      properties:
        id:
          type: integer
      example:
        id: 1
    SightingPreview:
      type: object
      properties:
        deathType:
          $ref: "#/components/schemas/DeathType"
        time:
          type: integer
          description: Time in milliseconds since the epoch (midnight of January 1, 1970, UTC)
    Sighting:
      allOf:
        - $ref: "#/components/schemas/SightingPreview"
        - type: object
        - properties:
            latitude:
              type: number
              format: double
            longitude:
              type: number
              format: double
            accuracy:
              type: number
              format: double
              description: Accuracy of the provided latitude and longitude values in meters
            notes:
              nullable: true
              type: string
              minLength: 1
              maxLength: 10000
