@hostname = bsh23.brighton.domains

### Send GET request without URL parameter
GET https://{{hostname}}/ci609/api/sightings/

> {%
    client.test("Missing URL parameter is a bad request", () => {
        client.assert(response.status === 400, "Response status is not 400");
    });
%}

### Send GET request with invalid sighting ID
GET https://{{hostname}}/ci609/api/sightings/abcd

> {%
    client.test("Non-numeric sighting ID is a bad request", () => {
        client.assert(response.status === 400, "Response status is not 400");
    });
%}

### Send GET request without results
GET https://{{hostname}}/ci609/api/sightings/0

> {%
    client.test("Request executed successfully", () => {
        client.assert(response.status === 404, "Response status is not 404");
    });

    client.test("Request with no results has empty response body", () => {
        client.assert(response.body === null, "Response body is not empty");
    });
%}